### PR TITLE
added 'Role' parameter to build only for a certain role

### PR DESCRIPTION
**Pull request by DeBasti**
Hi there,

I added a parameter in order to build the mof- and meta mof files only for a certain role.

Greetings,
Sebastian

### CODE REVIEW

**Comment by raandree** [comment]
Would it be better to have a Filter parameter that allows the user to select the node based on whatever is important? There are many more options you might want to filter on, like Country, Domain, etc.

**Comment by gaelcolas** [comment]
Thanks for the PR, much appreciated!

Filtering by node is already supported (but undocumented), using the parameter `$FilterNode`. This needs to be added to the .build.ps1 parameters should you wish to use it.

Whether a role filter should be present is a different question.
What's the use case and why?
When do you use it? 
What's the value?

It's not a bad idea, but I'd like to understand the underlying reasons.

The DSCInfraSample is just an example control repo that people should customise to their taste, and that's a great example anyway.

**Comment by raandree** [comment]
The use case is that you want to build only a subset of nodes. Imagine you have some thousand nodes and the change to the config is affecting only some nodes that you want to build the MOFs for. Especially in dev and test this could speed things up.

To have the max flexibility I would vote for a FilterScript parameter so the use case is not fixed.

**Comment by gaelcolas** [comment]
Yep, I was thinking the same. It should be a `-Filter` parameter...

**Comment by DeBasti** [comment]
You've got a point there. I implemented the filter parameter today (it's not yet pushed though). How is the usual procedure? Closing this pull request and raising a new one?

**Comment by gaelcolas** [comment]
If you made the change in the same branch, yes. Otherwise you can keep open and create new PR.
Please make sure you `git pull --rebase` from master.

**Pull request closed without merging**
